### ISSUE TITLE
[링크깨짐] 한국정보화진흥원 AI Hub의 한국어 대화 텍스트 데이터, 한국어-영어 번역(병렬) 말뭉치 텍스트 데이터 

### ISSUE THREAD

**Issue by hyeonsangjeon** [sce-tts/mimic-recording-studio#2]
안녕하세요. 
한국어 녹음 코퍼스 MD파일 링크가 깨져있습니다. 데이터 Raw 링크 정보를 알고 싶습니다. 
[korean_corpus.csv](https://github.com/sce-tts/mimic-recording-studio/blob/master/backend/prompts/korean_corpus.csv)

아래  split의 두번째 65가 의미하는 것을 찾고 있는데 공유해주실수 있나요?
[Example]
경영계획 수립 시 연간 판매계획을 근거하여 기초재고 및 재고계획을 반영한 연간 생산계획을 수립하는 과정이 필요합니다.	65

**Comment by rishubil** [comment]
> 한국어 녹음 코퍼스 MD파일 링크가 깨져있습니다.

깨진 링크는 2e3a4ffb1f390681a2e832705d7b10b0d9e0c630 에서 수정했습니다.

> 아래 split의 두번째 65가 의미하는 것을 찾고 있는데 공유해주실수 있나요?

문장 다음의 숫자는 해당 문장의 길이입니다.
